### ISSUE TITLE
Incorrect API Endpoint Link

### ISSUE THREAD

**Issue by waveywaves** [harshhhdev/snip#5]
Endpoint mentioned in API.md is not accessible 
https://github.com/harshhhdev/snip/blob/main/API.md?plain=1#L3

neither does
https://snip.place/api

**Comment by ibra** [comment]
1. @waveywaves  ah that's my bad, snip.au was the domain we were originally going for, fixed in d2e763bac8c0389d5f224b34b309ac0719f5d568!
2. it appears the endpoints are all working but just https://snip.place/api 404's, will see if we can do something about that
